server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  boot:
    message: "Hello, This is Department Service Test"

  jpa:
    hibernate:
      ddl-auto: update   # options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9092/eureka/
